version: 2

project_name: godirb

before:
  hooks:
    - go mod tidy
    - go generate ./...

builds:
  - id: godirb
    main: .
    binary: godirb

    env:
      - CGO_ENABLED=0

    goos:
      - linux
      - windows
      - darwin

    goarch:
      - amd64
      - arm64
      - "386"

archives:
  - id: default
    formats:
      - tar.gz

    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}

    format_overrides:
      - goos: windows
        formats:
          - zip

checksum:
  name_template: "{{ .ProjectName }}_{{ .Version }}_checksums.txt"

changelog:
  use: git
  sort: asc
  abbrev: -1
  format: "{{ .Message }}"
  title: "Changelog"

  filters:
    include:
      - '^(feat|feature)(\([^)]+\))?!?: .+'
      - '^fix(\([^)]+\))?!?: .+'
      - '^refactor(\([^)]+\))?!?: .+'

  groups:
    - title: "Features"
      regexp: '^.*(feat|feature)(\([^)]+\))?!?: .+'
      order: 0

    - title: "Bug fixes"
      regexp: '^.*fix(\([^)]+\))?!?: .+'
      order: 1

    - title: "Refactors"
      regexp: '^.*refactor(\([^)]+\))?!?: .+'
      order: 2

release:
  header: |
    ## {{ .ProjectName }} {{ .Tag }}

    This release includes:

  footer: |

    ---
    Released by GoReleaser.
