changelog:
  sort: asc

  filters:
    exclude:
      - '^Merge'
      - '^merge'
      - '^merge: resolve conflicts'
      - '^Update version$'
      - '^Initial commit$'
      - '^Init '
      - '^Untrack '
      - '^Add '

    include:
      - '^feat'
      - '^fix'
      - '^refactor'

  groups:
    - title: Features
      regexp: '^feat'
      order: 0

    - title: Bug fixes
      regexp: '^fix'
      order: 1

    - title: Refactors
      regexp: '^refactor'
      order: 2

  format: "{{ .Message }}"