package signature

import (
	"slices"
	"testing"

	"github.com/MyCode83/godirb/internal/transport"
)

func testResponse(
	statusCode int,
	headers map[string]string,
	title string,
	body string,
) transport.Response {
	return transport.Response{
		URL:        "https://example.com/random-path",
		StatusCode: statusCode,
		Headers:    headers,
		Title:      title,
		Body:       []byte(body),
	}
}

func TestMatcherDoesNotLoadCleanHTTPDefaultRules(t *testing.T) {
	matcher, err := New()
	if err != nil {
		t.Fatalf("New() error = %v", err)
	}

	response := testResponse(
		400,
		map[string]string{"Server": "CloudFront"},
		"ERROR: The request could not be satisfied",
		"The request could not be satisfied. Generated by cloudfront (CloudFront)",
	)

	matches := matcher.Match(&response)

	if len(matches) != 0 {
		t.Fatalf("Match() = %v, want no cleanhttp default-rule matches", matches)
	}
}

func TestMatcherLoadsCustomRules(t *testing.T) {
	matcher, err := New()
	if err != nil {
		t.Fatalf("New() error = %v", err)
	}

	tests := []struct {
		name      string
		signature string
		response  transport.Response
	}{
		{
			name:      "Nginx default 404",
			signature: "nginx_default_404",
			response: testResponse(
				200,
				map[string]string{"Server": "nginx/1.27.0"},
				"404 Not Found",
				"<center><h1>404 Not Found</h1></center>",
			),
		},
		{
			name:      "OpenResty default 404",
			signature: "openresty_default_404",
			response: testResponse(
				200,
				map[string]string{"Server": "openresty/1.25.3.1"},
				"404 Not Found",
				"<center><h1>404 Not Found</h1></center>",
			),
		},
		{
			name:      "Apache default 404",
			signature: "apache_default_404",
			response: testResponse(
				200,
				map[string]string{"Server": "Apache/2.4.62"},
				"404 Not Found",
				"The requested URL was not found on this server.",
			),
		},
		{
			name:      "IIS default 404",
			signature: "iis_default_404",
			response: testResponse(
				200,
				map[string]string{"Server": "Microsoft-IIS/10.0"},
				"404 - File or directory not found.",
				"The resource you are looking for might have been removed, "+
					"had its name changed, or is temporarily unavailable.",
			),
		},
		{
			name:      "Tomcat default 404",
			signature: "tomcat_default_404",
			response: testResponse(
				200,
				nil,
				"",
				"<h1>HTTP Status 404 – Not Found</h1>"+
					"<h3>Apache Tomcat/10.1.0</h3>",
			),
		},
		{
			name:      "Jetty default 404",
			signature: "jetty_default_404",
			response: testResponse(
				200,
				map[string]string{"Server": "Jetty(12.0.0)"},
				"",
				"HTTP ERROR 404 Not Found\nPowered by Jetty:// 12.0.0",
			),
		},
		{
			name:      "Caddy default 404",
			signature: "caddy_default_404",
			response: testResponse(
				200,
				map[string]string{"Server": "Caddy"},
				"",
				"404 page not found\n",
			),
		},
		{
			name:      "lighttpd default 404",
			signature: "lighttpd_default_404",
			response: testResponse(
				200,
				map[string]string{"Server": "lighttpd/1.4.76"},
				"404 - Not Found",
				"<h1>404 - Not Found</h1>",
			),
		},
		{
			name:      "Jenkins default 404 with header",
			signature: "jenkins_default_404",
			response: testResponse(
				200,
				map[string]string{"X-Jenkins": "2.516.1"},
				"",
				"HTTP ERROR 404 Not Found\n"+
					"SERVLET: Stapler\n"+
					"Powered by Jetty:// 12.0.0",
			),
		},
		{
			name:      "Jenkins default 404 without header",
			signature: "jenkins_default_404",
			response: testResponse(
				200,
				nil,
				"",
				"HTTP ERROR 404 Not Found\n"+
					"SERVLET: Stapler\n"+
					"Powered by Jetty:// 12.0.0",
			),
		},
		{
			name:      "Joomla default 404",
			signature: "joomla_default_404",
			response: testResponse(
				200,
				nil,
				"",
				"The requested page can't be found. Powered by Joomla!",
			),
		},
		{
			name:      "Amazon S3 missing key",
			signature: "amazon_s3_no_such_key",
			response: testResponse(
				200,
				map[string]string{"Server": "AmazonS3"},
				"",
				"<Code>NoSuchKey</Code>"+
					"<Message>The specified key does not exist.</Message>",
			),
		},
		{
			name:      "Azure missing blob",
			signature: "azure_blob_not_found",
			response: testResponse(
				200,
				map[string]string{"Server": "Windows-Azure-Blob/1.0"},
				"",
				"<Code>BlobNotFound</Code>",
			),
		},
		{
			name:      "Google Cloud Storage missing key",
			signature: "google_cloud_storage_no_such_key",
			response: testResponse(
				200,
				map[string]string{"Server": "UploadServer"},
				"",
				"<Code>NoSuchKey</Code>"+
					"<Message>The specified key does not exist.</Message>",
			),
		},
		{
			name:      "GitHub Pages missing site",
			signature: "github_pages_site_not_found",
			response: testResponse(
				200,
				map[string]string{"Server": "GitHub.com"},
				"",
				"There isn't a GitHub Pages site here.",
			),
		},
		{
			name:      "Fastly unknown domain",
			signature: "fastly_unknown_domain",
			response: testResponse(
				200,
				nil,
				"",
				"Fastly error: unknown domain: example.invalid",
			),
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			matches := matcher.Match(&tt.response)

			if !slices.Contains(matches, tt.signature) {
				t.Fatalf(
					"Match() = %v, want %q",
					matches,
					tt.signature,
				)
			}
		})
	}
}

func TestMatcherDoesNotFilterPotentiallyRealResponses(t *testing.T) {
	matcher, err := New()
	if err != nil {
		t.Fatalf("New() error = %v", err)
	}

	tests := []struct {
		name     string
		response transport.Response
	}{
		{
			name: "Nginx forbidden endpoint",
			response: testResponse(
				403,
				map[string]string{"Server": "nginx/1.27.0"},
				"403 Forbidden",
				"<center><h1>403 Forbidden</h1></center>",
			),
		},
		{
			name: "Apache forbidden endpoint",
			response: testResponse(
				403,
				map[string]string{"Server": "Apache/2.4.62"},
				"403 Forbidden",
				"You don't have permission to access this resource.",
			),
		},
		{
			name: "Cloudflare access denied",
			response: testResponse(
				403,
				map[string]string{"Server": "cloudflare"},
				"Access denied",
				"Error 1020 Access denied",
			),
		},
		{
			name: "Nginx bad gateway",
			response: testResponse(
				502,
				map[string]string{"Server": "nginx/1.27.0"},
				"502 Bad Gateway",
				"<center><h1>502 Bad Gateway</h1></center>",
			),
		},
		{
			name: "Jenkins dashboard",
			response: testResponse(
				200,
				map[string]string{"X-Jenkins": "2.516.1"},
				"Dashboard [Jenkins]",
				"Welcome to Jenkins",
			),
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			matches := matcher.MatchDefaultError(&tt.response)

			if len(matches) != 0 {
				t.Fatalf(
					"MatchDefaultError() = %v, potentially real response must not be filtered",
					matches,
				)
			}
		})
	}
}

func TestMatcherDoesNotFilterGenericTechnologyFingerprints(t *testing.T) {
	matcher, err := New()
	if err != nil {
		t.Fatalf("New() error = %v", err)
	}

	response := testResponse(
		200,
		map[string]string{"Server": "CloudFront"},
		"Real asset",
		"real javascript bundle",
	)

	matches := matcher.MatchDefaultError(&response)
	if len(matches) != 0 {
		t.Fatalf("MatchDefaultError() = %v, want none", matches)
	}
}
