package core

var openServiceSignals = []string{
	"first record does not look like a tls handshake",
	"server gave http response to https client",
	"tls: oversized record",
	"tls: record overflow",
	"tls: unexpected message",
	"tls: unexpected record",
	"tls: malformed record",
	"tls: invalid record",
	"tls: handshake failure",
	"tls: protocol version not supported",
	"tls: unsupported protocol version",
	"tls: no application protocol",
	"tls: unrecognized name",
	"tls: bad certificate",
	"tls: certificate required",
	"tls: unknown certificate",
	"tls: unsupported certificate",
	"tls: certificate revoked",
	"tls: certificate expired",
	"tls: decrypt error",
	"tls: decryption failed",
	"tls: decode error",
	"tls: illegal parameter",
	"tls: access denied",
	"tls: internal error",
	"tls: user canceled",
	"tls: no renegotiation",
	"tls: missing extension",
	"tls: unsupported extension",
	"tls: inappropriate fallback",
	"tls: insufficient security",
	"tls: unexpected handshake message",
	"tls: unexpected certificate",
	"tls: unexpected server key exchange",
	"tls: unexpected certificate request",
	"tls: unexpected new session ticket",
	"tls: unexpected encrypted extensions",
	"tls: unexpected key update",
	"tls: invalid handshake",
	"tls: invalid message",
	"tls: invalid certificate",
	"tls: invalid signature",
	"tls: invalid renegotiation",
	"tls: invalid next protocol",
	"tls: invalid alpn protocol",
	"tls: duplicate extension",
	"tls: unrequested extension",
	"tls: server selected unsupported protocol",
	"tls: server selected unsupported cipher suite",
	"tls: server chose an unconfigured cipher suite",
	"tls: server chose an unsupported cipher suite",
	"tls: server sent an incorrect legacy version",
	"tls: server sent an invalid session ticket",
	"remote error: tls",
	"local error: tls",

	"connection reset by peer",
	"connection reset",
	"forcibly closed by the remote host",
	"connection was forcibly closed",
	"an existing connection was forcibly closed",
	"wsarecv: an existing connection was forcibly closed",
	"wsasend: an existing connection was forcibly closed",
	"connection aborted by host",
	"software caused connection abort",
	"connection aborted",
	"broken pipe",
	"connection closed by remote host",
	"remote host closed the connection",
	"peer closed connection",
	"server closed connection",
	"server closed idle connection",
	"use of closed network connection",
	"closed network connection",

	"unexpected eof",
	"eof",

	"malformed http response",
	"malformed http status code",
	"malformed response",
	"malformed mime header",
	"invalid http response",
	"invalid http status code",
	"invalid response status",
	"invalid response",
	"invalid header field",
	"invalid header field name",
	"invalid header field value",
	"invalid byte in header",
	"invalid byte in chunk length",
	"invalid character in header",
	"invalid chunked encoding",
	"invalid content-length",
	"invalid transfer encoding",
	"invalid trailer",
	"unexpected trailer",
	"bad status line",
	"bad response",
	"bogus greeting",
	"header line too long",
	"response line too long",
	"too many headers",
	"too many informational responses",
	"server response headers exceeded",
	"response headers exceeded",
	"chunked line ends with bare lf",
	"mime: malformed",
	"http: invalid",
	"unsupported transfer encoding",
	"unsupported protocol scheme",

	"http2: invalid",
	"http2: frame too large",
	"http2: connection error",
	"http2: stream error",
	"http2: server sent",
	"http2: unexpected",
	"received goaway",
	"protocol error",
}